# 1) Data Manipulation [Getting started]

In [8]:
import torch

## Creating Tensors

A *tensor* represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor is called a *vector*. With two axes, a tensor is called a *matrix*. With $k > 2$ axes, we
drop the specialized names and just refer to the object as a *$k^\text{th}$ order tensor*.

In torch, there are several functions for creating new tensors prepopulated with values. For example, by invoking arange(n), we can create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included). By default, the interval size is 1. 

In [9]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Each of these values is called an element of the tensor. The tensor x contains 12 elements.
We can inspect the total number of elements in a tensor via its numel **method**.

In [20]:
x.numel()

12

We can access a tensor’s shape (the length along each axis) by inspecting its shape **attribute**.
Because we are dealing with a vector here, the shape contains just a single element and is
identical to the size.

In [22]:
x.shape

torch.Size([12])

We can change the shape of a tensor without altering its size or values, by invoking reshape (**method**).
For example, we can transform our vector x whose shape is (12,) to a matrix X with shape (3,
4). This new tensor retains all elements but reconfigures them into a matrix.

In [33]:
y=x.reshape(3,4)
y 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

Notice that the elements of our vector are laid out one row at a time and thus x[3] == y[0,3].

In [37]:
print(x[3])
print(y[0,3])
x[3]==y[0,3]

tensor(3.)
tensor(3.)


tensor(True)

Note that specifying every shape component to reshape is redundant. Because we already
know our tensor’s size, we can work out one component of the shape given the rest. 

To automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically. In our case, instead of calling x.reshape(3, 4), we could have
equivalently called x.reshape(-1, 4) or x.reshape(3, -1).

In [49]:
print(x.reshape(3,4)==x.reshape(-1,4))
print("----------------------------------")
print(x.reshape(3,4)==x.reshape(3,-1))

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
----------------------------------
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Frecuently used tensors

Practitioners often need to work with tensors initialized to contain all zeros or ones. We
can construct a tensor with all elements set to zero and a shape of (2, 3, 4) via the **zeros
function**.

In [51]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Similarly, we can create a tensor with all ones by invoking **ones**.

In [52]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We often wish to sample each element **randomly** (and independently) from a given probability
distribution. For example, the parameters of neural networks are often initialized randomly.
The following snippet creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.


In [53]:
torch.randn(3, 4)

tensor([[-1.7191,  2.4488,  0.3148, -1.1190],
        [ 0.1569,  1.0005, -0.6721,  0.9294],
        [ 0.4815, -1.5686, -0.4963, -0.1362]])

Finally, we can construct tensors by supplying the exact values for each element by supplying
(possibly nested) Python list(s) containing numerical literals. Here, we construct a matrix
with a list of lists, where the outermost list corresponds to axis 0, and the inner list to axis
1.

In [55]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])